source 'https://rubygems.org'

gem 'jekyll'
gem 'compass'
gem 'capybara'
gem "minitest-capybara"
gem 'poltergeist'
gem 'sinatra'
gem 'addressable'
gem 'pry'
gem 'aws-sdk'
gem 'rake'
gem 'rack-jekyll'
